### PR TITLE
Improve VideoPoker bet management

### PR DESCRIPTION
**Pull request by dsmatilla**
Fix: Max bet exceeded the limit by 10 when pressing right
Feat: Left on min bet now goes to max bet, right on max bet goes to min bet
Feat: Up now goes all-in

This was slightly bothering me while playing, so I fixed it 😄

### CODE REVIEW

**Comment by ChromeBlue** [comment]
It would be great if it would save the credits when exiting.

**Comment by dsmatilla** [comment]
> It would be great if it would save the credits when exiting.

You guys are leaving the game with credits? 😢 

I always end up with 0.

**Comment by xMasterX** [comment]
> It would be great if it would save the credits when exiting.

I can add simple saving of credits, but there will be no way to reset them in app, only by removing save file
Is that good idea? Or better to left it as is?

**Comment by xMasterX** [comment]
> Fix: Max bet exceeded the limit by 10 when pressing right Feat: Left on min bet now goes to max bet, right on max bet goes to min bet Feat: Up now goes all-in
> 
> This was slightly bothering me while playing, so I fixed it 😄

Thanks

**Comment by ChromeBlue** [comment]
> > It would be great if it would save the credits when exiting.
> 
> You guys are leaving the game with credits? 😢 
> 
> I always end up with 0.

You might want to avoid Vegas like an F1 driver.

Yes, I had 18K+ credits when I shut diwn.

**Comment by ChromeBlue** [comment]
> > It would be great if it would save the credits when exiting.
> 
> I can add simple saving of credits, but there will be no way to reset them in app, only by removing save file
> Is that good idea? Or better to left it as is? 

Cool by me!

**Pull request merged**
